# Generated by Django 4.1.3 on 2022-12-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('preferred_skills', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('company', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('inactive_date', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tindev.recruiterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=500)),
                ('years_experience', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('interested', models.ManyToManyField(blank=True, null=True, to='tindev.createpost')),
            ],
        ),
    ]
