# Generated by Django 4.1.3 on 2022-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tindev", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createpost",
            name="inactive_date",
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="bio",
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="github",
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createpost",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
