# Generated by Django 4.1.3 on 2022-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tindev",
            "0002_remove_createpost_inactive_date_candidateprofile_bio_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="education",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="github",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="createpost",
            name="is_active",
            field=models.BooleanField(
                choices=[("False", "F"), ("True", "T")], default=True
            ),
        ),
    ]
