# Generated by Django 4.1.3 on 2022-11-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0002_auto_20221117_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('preferred_skills', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('company', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
                ('inactive_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
