# Generated by Django 4.1.3 on 2022-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tindev", "0003_alter_candidateprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createpost",
            name="is_active",
            field=models.BooleanField(
                choices=[("False", "False"), ("True", "True")], default=True
            ),
        ),
    ]
