# Generated by Django 4.1.3 on 2022-12-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tindev", "0003_createpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createpost",
            name="expiration_date",
            field=models.DateTimeField(verbose_name="Expiration Date (DD/MM/YEAR)"),
        ),
        migrations.AlterField(
            model_name="createpost",
            name="inactive_date",
            field=models.DateTimeField(verbose_name="Inactive Date (DD/MM/YEAR)"),
        ),
        migrations.AlterField(
            model_name="createpost",
            name="is_active",
            field=models.BooleanField(),
        ),
    ]
