# Generated by Django 4.1.3 on 2022-12-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tindev", "0004_alter_createpost_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="zip_code",
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.CharField(max_length=50)),
                ("due_date", models.DateField()),
                (
                    "acepted",
                    models.BooleanField(
                        blank=True, choices=[("False", "False"), ("True", "True")]
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tindev.candidateprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tindev.createpost",
                    ),
                ),
            ],
        ),
    ]
