# Generated by Django 4.1.3 on 2022-12-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tindev", "0004_alter_createpost_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createpost",
            name="recruiter",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="tindev.recruiterprofile",
            ),
            preserve_default=False,
        ),
    ]
