# Generated by Django 4.1.3 on 2022-12-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0005_alter_candidateprofile_zip_code_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='acepted',
            field=models.BooleanField(blank=True, choices=[('False', 'False'), ('True', 'True')], null=True),
        ),
    ]
