# Generated by Django 4.1.3 on 2022-12-07 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0007_alter_offers_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tindev.createpost'),
        ),
    ]
