# Generated by Django 4.1.3 on 2022-12-07 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0008_alter_offers_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tindev.candidateprofile'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tindev.createpost'),
        ),
    ]
